# Generated by Django 3.0.6 on 2020-05-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_pedal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rfid',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
