# Generated by Django 3.0.6 on 2020-05-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullcalendar', '0001_initial'),
        ('users', '0003_auto_20200505_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='events',
            field=models.ManyToManyField(blank=True, to='fullcalendar.CalendarEvent'),
        ),
    ]
